#%RAML 1.0
---

title: Mobile Tax Credits Renewal
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile-tax-credits-renewal:
  /claimants:
    /{nino}:
      uriParameters:
        nino:
          description: The NINO for the individual.
          type: string
          example: NS123456B
      get:
        displayName: Get claimant details
        description: This endpoint retrieves the claimant details.
        is: [headers.acceptHeader]
        (annotations.scope): "read:mobile-tax-credits-renewal"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-tax-credits-renewal" ] } ]
        queryParameters:
          journeyId:
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/claimants-example.json
  /claims:
    /{nino}:
      uriParameters:
        nino:
          description: The NINO for the individual.
          type: string
          example: NS123456B
      get:
        displayName: Get claims details
        description: This endpoint retrieves the claims details.
        is: [headers.acceptHeader]
        (annotations.scope): "read:mobile-tax-credits-renewal"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-tax-credits-renewal" ] } ]
        queryParameters:
          journeyId:
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/claims-example.json
  /declarations:
    /{nino}:
      uriParameters:
        nino:
          description: The NINO for the individual.
          type: string
          example: NS123456B
      post:
        displayName: Submit renewal
        description: This endpoint submits a renewal.
        is: [headers.acceptHeader]
        (annotations.scope): "read:mobile-tax-credits-renewal"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-tax-credits-renewal" ] } ]
        queryParameters:
          journeyId:
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/declarations-example.json
  /states:
    /current:
      get:
        displayName: Get tax credits submission state enabled
        description: This endpoint retrieves the current state of tax credit submissions
        is: [headers.acceptHeader]
        (annotations.scope): "read:mobile-tax-credits-renewal"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-tax-credits-renewal" ] } ]
        queryParameters:
          journeyId:
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/states-current-example.json
  /tokens:
    /{nino}:
      uriParameters:
        nino:
          description: The NINO for the individual.
          type: string
          example: NS123456B
      /{renewalReference}:
        uriParameters:
          renewalReference:
            type: string
        get:
          displayName: Get auth token
          description: This endpoint retrieves the auth token and validates the nino and tax reference number.
          is: [headers.acceptHeader]
          (annotations.scope): "read:mobile-tax-credits-renewal"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-tax-credits-renewal" ] } ]
          queryParameters:
            journeyId:
              type: string
              required: false
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/tokens-example.json



