openapi: 3.0.0
info:
  title: Mobile Tax Credits Renewal
  description: >-
    ### What is this API for?

    The API is used to retrieve and update tax credits renewal information.
  contact: {}
  version: '1.0'
servers:
  - url: https://test-api.service.hmrc.gov.uk/mobile-tax-credits-renewal
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/mobile-tax-credits-renewal
    description: Production
    variables: {}
paths:
  /mobile-tax-credits-renewal/income/tax-credits/submission/state/enabled:
    get:
      tags:
        - mobile-tax-credits-renewal
      summary: Get tax credits submission state enabled
      description: This endpoint retrieves the current state of tax credit submissions
      operationId: Gettaxcreditssubmissionstateenabled
      parameters:
        - name: journeyId
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MobileTaxCreditsRenewalIncomeTaxCreditsSubmissionStateEnabledresponse'
                  - example:
                      submissionsState: open
              examples:
                example-1:
                  value:
                    submissionsState: open
      deprecated: false
      security:
        - userRestricted:
            - read:native-apps-api-orchestration
  /mobile-tax-credits-renewal/income/{nino}/tax-credits/full-claimant-details:
    get:
      tags:
        - mobile-tax-credits-renewal
      summary: Get full claiment details
      description: This endpoint retrieves the full claiment details.
      operationId: Getfullclaimentdetails
      parameters:
        - name: nino
          in: path
          description: The NINO for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: NS123456B
        - name: journeyId
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MobileTaxCreditsRenewalIncomeTaxCreditsFullClaimantDetailsresponse'
                  - example:
                      references:
                        - household:
                            barcodeReference: '200000000000013'
                            applicationID: '198765432134567'
                            applicant1:
                              nino: CS700100A
                              title: MR
                              firstForename: JOHN
                              secondForename: ''
                              surname: DENSMORE
                            householdEndReason: ''
                          renewal:
                            awardStartDate: 12/10/2030
                            awardEndDate: 12/10/2010
                            renewalStatus: NOT_SUBMITTED
                            renewalNoticeIssuedDate: 12/10/2030
                            renewalNoticeFirstSpecifiedDate: 12/10/2010
                            renewalFormType: D
              examples:
                example-1:
                  value:
                    references:
                      - household:
                          barcodeReference: '200000000000013'
                          applicationID: '198765432134567'
                          applicant1:
                            nino: CS700100A
                            title: MR
                            firstForename: JOHN
                            secondForename: ''
                            surname: DENSMORE
                          householdEndReason: ''
                        renewal:
                          awardStartDate: 12/10/2030
                          awardEndDate: 12/10/2010
                          renewalStatus: NOT_SUBMITTED
                          renewalNoticeIssuedDate: 12/10/2030
                          renewalNoticeFirstSpecifiedDate: 12/10/2010
                          renewalFormType: D
      deprecated: false
      security:
        - userRestricted:
            - read:native-apps-api-orchestration
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user-restricted API requests using an OAuth 2.0 Bearer Token in the
        AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:native-apps-api-orchestration: Expose APIs to app for tax credits renewal services.
  schemas:
    Applicant1:
      title: Applicant1
      required:
        - nino
        - title
        - firstForename
        - secondForename
        - surname
      type: object
      properties:
        nino:
          type: string
        title:
          type: string
        firstForename:
          type: string
        secondForename:
          type: string
        surname:
          type: string
      example:
        nino: AA000000A
        title: MR
        firstForename: JOHN
        secondForename: ''
        surname: DENSMORE
    Household:
      title: Household
      required:
        - barcodeReference
        - applicationID
        - applicant1
        - householdEndReason
      type: object
      properties:
        barcodeReference:
          type: string
        applicationID:
          type: string
        applicant1:
          $ref: '#/components/schemas/Applicant1'
        householdEndReason:
          type: string
      example:
        barcodeReference: '200000000000013'
        applicationID: '198765432134567'
        applicant1:
          nino: AA000000A
          title: MR
          firstForename: JOHN
          secondForename: ''
          surname: DENSMORE
        householdEndReason: ''
    MobileTaxCreditsRenewalIncomeTaxCreditsFullClaimantDetailsresponse:
      title: MobileTaxCreditsRenewalIncomeTaxCreditsFullClaimantDetailsresponse
      required:
        - references
      type: object
      properties:
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
          description: ''
      example:
        references:
          - household:
              barcodeReference: '200000000000013'
              applicationID: '198765432134567'
              applicant1:
                nino: CS700100A
                title: MR
                firstForename: JOHN
                secondForename: ''
                surname: DENSMORE
              householdEndReason: ''
            renewal:
              awardStartDate: 12/10/2030
              awardEndDate: 12/10/2010
              renewalStatus: NOT_SUBMITTED
              renewalNoticeIssuedDate: 12/10/2030
              renewalNoticeFirstSpecifiedDate: 12/10/2010
              renewalFormType: D
    MobileTaxCreditsRenewalIncomeTaxCreditsSubmissionStateEnabledresponse:
      title: MobileTaxCreditsRenewalIncomeTaxCreditsSubmissionStateEnabledresponse
      required:
        - submissionsState
      type: object
      properties:
        submissionsState:
          type: string
      example:
        submissionsState: open
    Reference:
      title: Reference
      required:
        - household
        - renewal
      type: object
      properties:
        household:
          $ref: '#/components/schemas/Household'
        renewal:
          $ref: '#/components/schemas/Renewal1'
      example:
        household:
          barcodeReference: '200000000000013'
          applicationID: '198765432134567'
          applicant1:
            nino: CS700100A
            title: MR
            firstForename: JOHN
            secondForename: ''
            surname: DENSMORE
          householdEndReason: ''
        renewal:
          awardStartDate: 12/10/2030
          awardEndDate: 12/10/2010
          renewalStatus: NOT_SUBMITTED
          renewalNoticeIssuedDate: 12/10/2030
          renewalNoticeFirstSpecifiedDate: 12/10/2010
          renewalFormType: D
    Renewal1:
      title: Renewal1
      required:
        - awardStartDate
        - awardEndDate
        - renewalStatus
        - renewalNoticeIssuedDate
        - renewalNoticeFirstSpecifiedDate
        - renewalFormType
      type: object
      properties:
        awardStartDate:
          type: string
        awardEndDate:
          type: string
        renewalStatus:
          type: string
        renewalNoticeIssuedDate:
          type: string
        renewalNoticeFirstSpecifiedDate:
          type: string
        renewalFormType:
          type: string
      example:
        awardStartDate: 12/10/2030
        awardEndDate: 12/10/2010
        renewalStatus: NOT_SUBMITTED
        renewalNoticeIssuedDate: 12/10/2030
        renewalNoticeFirstSpecifiedDate: 12/10/2010
        renewalFormType: D
tags:
  - name: mobile-tax-credits-renewal
    description: ''
